### ISSUE TITLE
Migrar site atual para estático

### ISSUE THREAD

**Issue by vanessametonini** [MariaLabHackerspace/web#1]
Migrar site atual para um html estático, com o mesmo layout a principio.

**Comment by miguelzinhe** [comment]
Quando você diz "migrar" seria refazer o HTML estático que está no ar?

**Comment by anarute** [comment]
Opa, topo ajudar! 
já tem alguma tecnologia definida? jekyll, hugo? html puro?
vi que hoje tá em WP

**Comment by vanessametonini** [comment]
@oieusouamiguel isso mesmo! fazer uma cópia do site em HTML estático

**Comment by vanessametonini** [comment]
@anarute a ideia é sair dos CMS e ter um site estático. pra descomplicar possíveis contribuições. não temos tecnologias para deploy/ci - seria legal pensar nisso tbm. mas pode ficar pra uma issue 2 :D

**Comment by vanessametonini** [comment]
coloquei um package.json para gerenciar bilbiotecas de terceiros caso necessario, por exemplo bootstrap

**Comment by miguelzinhe** [comment]
ok, vou fazer o html estático! <3 seria legal a gente pensar nessas dependencias mesmo pras proximas issues

na minha opiniao, jekyll seria bacana pro site do marialab, hein? a gente usa no codamos e é show de bola.

**Comment by vanessametonini** [comment]
acho que se as coisas complicarem podemos fazer upgrade pra um jekyll sim :D mas como o site ta bem simples. nem tem nem motivo pra ser wordpress.

**Comment by miguelzinhe** [comment]
Mandei PR <3
